log_file_name: logs.log  # Default name of the log file
exams_file: exams_file.xlsx  # Exams file name, should be in inputs directory
proctors_file: proctor_file.xlsx  # Proctors file name, should be in inputs directory
